version: '3.8'
# Fix: normalized spacing around project name key
name: mernapp

services:
  mongo:
     image: mongo:6
     container_name: mongodb
     ports:
       - "27017:27017"
     volumes:
       - mongo_data:/data/db
     networks:
       - mernapp
  
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app
      - /app/node_modules
    networks:
      - mernapp
    ports:
      - "8080:8080"
    depends_on:
      - mongo
    command: npm run dev
  
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    
    volumes:
      # Fix: add missing space after dash in host path mapping
      - ./frontend:/app
      - /app/node_modules
    networks:
      - mernapp
    # Change: bind Vite dev server to 0.0.0.0 for access from host
    command: npm run dev -- --host
    ports:
      - "5173:5173"
    depends_on:
      - backend
    
  
volumes:
  mongo_data:

networks:
   mernapp:
      # Fix: normalized spacing for driver value
      driver: bridge